### PR TITLE
Invoke creation of credentials rather than immediate failure, plus followup items for pr2005

### LINKED ISSUE #2022: Minor cleanup following PR #2005
https://github.com/posit-dev/publisher/pull/2005

- return entire credential object: https://github.com/posit-dev/publisher/pull/2005#discussion_r1688854406
- split logic to initiate deploy: https://github.com/posit-dev/publisher/pull/2005#discussion_r1688871639
- value check needed? https://github.com/posit-dev/publisher/pull/2005#discussion_r1688894458
- publish without credential didn't prompt for creation of one: https://github.com/posit-dev/publisher/pull/2005#pullrequestreview-2195268038

### PR DESCRIPTION
**Pull request by sagerb**
## Intent

resolves #2022 

This PR started out with implementing some simple updates requested within PR #2005. However, one of the comments questioned the failures during a few of the flows when there were no credentials available to the deployment record. A solution is provided for that problem as well, which makes a change to the workflows.

Those impacted scenarios are:
- Prompt for credentials when publishing entrypoint - when single deployment or compatible selected deployment has no credential.
- ~~Prompt for credentials during selectNewOrExistingConfig, when missing.~~

## Type of Change

- - [ ] Bug Fix 
- - [x] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [x] Refactor 
- - [ ] Tooling 

## Approach

Each of the changes has been committed separately. This should help facilitate the easiest review. There is not much overlap, if at all.

## Directions for Reviewers

Exercise the scenarios with and without credentials available to the selected deployments, to confirm the behavior. There should not be a scenario in which they are performing the operations indicated where they receive the old error message that there are no credentials for this server. (Although that can be displayed within the HomeView.)

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

**Review by dotNomad — APPROVED** [review]
I really liked being prompted for a Credential when attempting to publish with the Entrypoint button, but the prompt to create one when selecting or creating a Configuration felt disjointed to me.

I'd be curious to hear others' opinions on that.

**Comment by sagerb** [comment]
@dotNomad 

We can certainly remove the last one, if that is desired. I did it for completeness.

I did wonder if we should update the titles to indicate why we were prompting the user to create one, in all of the scenarios.

**Comment by mmarchetti** [comment]
> the prompt to create one when selecting or creating a Configuration felt disjointed to me

Since we don't need the credential yet, it does seem a little odd to ask for it.

**Comment by dotNomad** [comment]
> We can certainly remove the last one, if that is desired. I did it for completeness.

I would remove it from this PR. It is the only bit we have a bit of discussion around, and we can easily make another PR for it.

**Comment by sagerb** [comment]
Reverted last commit as requested! 
https://github.com/posit-dev/publisher/pull/2026/commits/f965f90a7f07fc60f309b13d34db5522a920b81e

**Pull request merged**
