### PR TITLE
Suppress permission errors

### LINKED ISSUE #2135: Opening a directory with no detectable entrypoints throws confusing errors
When I open a directory with no detectable entrypoints, I'm able to click the `Select...` dropdown.  Three errors are thrown and the Create New Deployment dropdown still displays.  If I then click `Create New Deployment` then I get a fourth error saying an entrypoint cannot be detected.

Error 1:
 ```
An error has occurred at refreshContentRecordData::contentRecords.getAll, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/get//deployments
```

Error 2:
```
An error has occurred at refreshAll::Promise.all, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/get//deployments
```

Error 3: 
```
An error has occurred at refreshConfigurationData::configurations.getAll, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/get//configurations
```

Error 4 (after clicking Create New Deployment):
```
Unable to continue with project entrypoint detection failure. An error has occurred at newDeployment, entrypoints.get, StatusText=Internal Server Error, Code=ERR_BAD_RESPONSE, Msg=open /Users/kgartland/.Trash: operation not permitted, URL=http://localhost:57521/api/post//entrypoints
```

Instead can we catch this earlier when the Publisher is displayed, throw Error 4 and make the `Select...` dropdown inactive?

### PR DESCRIPTION
**Pull request by mmarchetti**
## Intent

This PR adds handling for permission errors during directory traversal.

Fixes #2135 

## Type of Change

- - [x] Bug Fix 
- - [ ] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [ ] Refactor 
- - [ ] Tooling 

## Approach

The `MatchingWalker` and `filesService` suppress permission errors.

## Directions for Reviewers

Deny read permissions to files or directories in your project (`chmod 000 $PATH`).

* Directories that can't be read will show up as empty in the Project Files view. 
* Files that can't be read will show up in the Project Files view. If you exclude them, you can deploy without error. If you include them, an error will be raised during deployment.

This is similar to the VSCode file tree behavior.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

**Comment by sagerb** [comment]
I can confirm that deployment does stop with the error as expected. 

2024-08-28 at 3 24 PM

But the files view is not showing a directory w/ permissions issues as a directory (it doesn't have a chevron).

I created the following directory and files within my project:
```
~/dev/connect-content/bundles/python-shiny-express main > mkdir no-rights
~/dev/connect-content/bundles/python-shiny-express main > mkdir rights
~/dev/connect-content/bundles/python-shiny-express main > cd rights
~/dev/connect-content/bundles/python-shiny-express/rights main > touch no-touchy.txt
~/dev/connect-content/bundles/python-shiny-express/rights main > chmod 000 no-touchy.txt 
~/dev/connect-content/bundles/python-shiny-express/rights main > cd ..
~/dev/connect-content/bundles/python-shiny-express main > chmod 000 no-rights
```

And our file view showed:
2024-08-28 at 3 15 PM

In using this, I do think it should work slightly different:

My observations:
1. I would think that the directory should not be selectable and that the tooltip shows the reason why.
2. I would expect that we should disable the files which we don't have permission for and give a reason that it cannot be included within the tooltip.

**Review by sagerb — CHANGES_REQUESTED** [review]
code looks great to handle permission error, but I think we want a change in the UX and I'm not sure if that will require a change in the agent or not. See my comment that describes my verification experience.

If we want to address those changes in a separate PR, let me know and I will approve this one.

**Comment by sagerb** [comment]
It does also appear that you are fairly behind on `main`... so I pushed a merge update into it for you. I noticed that the file inclusion/exclusion wasn't inserting the forward slash into the files array... and was worried we somehow broke that. But after the merge, it worked as expected.

**Comment by mmarchetti** [comment]
Thank you for reviewing. The directory showing up without the chevron is definitely a bug, I'll take a look. Having the file show up with an exclusion reason will be trickier, because we aren't opening files when scanning - we only `stat` them, so we don't know whether we could successfully open them.

**Comment by sagerb** [comment]
> Thank you for reviewing. The directory showing up without the chevron is definitely a bug, I'll take a look. Having the file show up with an exclusion reason will be trickier, because we aren't opening files when scanning - we only `stat` them, so we don't know whether we could successfully open them.

But having that permission error, isn't that enough for us to exclude them, that they won't go up? I'm just thinking we don't allow selection with a permission error (although I guess that is also confusing if the user has the file already listed in the files array).

**Comment by mmarchetti** [comment]
We don't detect permission errors for files in the Files API (only directories). We open/read directories in order to traverse them, which is when the error becomes visible. We don't open each file, because it would be very slow for large directories, so we don't get permission errors back for those.

We can handle permission errors during bundle creation by skipping affected files and logging. As you mentioned, this might be confusing if you've selected a file for inclusion and it can't be read, but files in your workspace that you can't read should be pretty rare. And it's likely that you might have tried to open the file in VSCode at some point, which would pop up an error.

**Comment by sagerb** [comment]
> the file in VSCode at some point, which would pop up an error...

Ah, ok, thanks for the clarification. Then I'm good with not worrying about the exclusion reasons for files but since a directory with permission errors is empty, we might want to think about (in a future PR) passing an exclusion reason for that (if you haven't already implemented that).

Let me re-verify your latest change.

**Review by sagerb — APPROVED** [review]
With the recent changes, the expected functionality works great. Directory w/ permission errors is showing as an empty directory, and as seen below, deployment detects/shows a permission error when deploying.

2024-08-29 at 9 06 AM

Even better if you see the posit publisher log!

2024-08-29 at 9 09 AM

**Review by dotNomad — APPROVED** [review]
Fantastic changes. Frontend looks great as well.

**Comment by kgartland-rstudio** [comment]
Verified errors in the original issue https://github.com/posit-dev/publisher/issues/2135 no longer occur.

**Pull request merged**
