### PR TITLE
Improve Quarto websites projects inspection and generated configuration 

### LINKED ISSUE #2266: Quarto Website not deploying as expected
## Update (while trying to reproduce)

While trying to reproduce this issue, found that the work for enabling Quarto scripts (#2424) also helped on Quarto websites, with a couple items still requiring work:
1. Pre and Post render scripts are not automatically picked up to be added to the configuration on project inspection
2. Users selecting `_quarto.yml` as entrypoint would get an undesired outcome (`unknown` type project). This because `quarto inspect` does not work on `_quarto.yml` files but it is understandable that the user picks that file and by doing so the project type is explicit enough already.

## Original

From: https://positpbc.slack.com/archives/C05D7NZD52S/p1726064950810009

I have a Quarto website project. I don’t really understand what needs to be considered the “entrypoint” in this context. I’m given my *.qmd files, my *.py pre-render script, and one rendered HTML file, but the _quarto.yml file (which is the closest option in my mental model) isn’t offered.

Image

I want to deploy this project as source (not rendered) and include the files:
- _quarto.yml
- requirements.txt
- index.qmd, visualize-r.qmd, visualize-py.qmd
- allocation.py
This project has both R and Python package requirements.

Proceeding with the deployment workflow, it missed the pre-render allocation.py script and did not identify that the project requires R as well as Python.
The Quarto inspect output DOES say that knitr is used:
```
  "engines": [
    "jupyter",
    "markdown",
    "knitr"
  ],
```

I tried to guess about the [r] syntax:
```
[r]
version = '4.3.3'
```

 I got an ugly error (attached).
The TOML was updated with placeholders which also violated the configuration:
```
[r]
version = '4.3.3'
package_file = ''
package_manager = ''
```

Image

I tried to `package_manager = 'none'` and got a complaint when trying to deploy; I was trying to use my standard library, not renv.

Image

:cry: The deployed manifest does not indicate that Quarto needs the knitr engine and therefore does not cause Connect to install R packages.

```
	"quarto": {
		"version": "1.5.57",
		"engines": [
			"jupyter",
			"markdown"
		]
	},
```

For those following along, I was able to successfully deploy with:
```
rsconnect::deployApp(server = "rsc.radixu.com", account = "aron", python = file.path(getwd(), "env/bin/python"))
```

This one is a little awkward because it doesn’t use reticulate. Instead, it uses both the knitr and jupyter engines. rsconnect could do better at detecting the need for Python in this situation.

Note: I still have `package_manager = 'none'` but renv was required.

See slack link for archive of project, created with:
```
tar cf mixed.tar --exclude mixed/_site --exclude mixed/env --exclude mixed/renv/library --exclude mixed/.quarto mixed
```

My Python virtual env was in `env`.

### PR DESCRIPTION
**Pull request by marcosnav**
## Intent

The goal of this PR is to improve the experience of Quarto website projects. Focused in two main points:
1. `pre-` and `post-` scripts are now automatically picked up to be added to the configuration on project inspection.
2. Users can select `_quarto.yml` as entrypoint and configuration will be properly generated.

Fixes #2266 

## Type of Change

- - [x] Bug Fix 
- - [ ] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [ ] Refactor 
- - [ ] Tooling 

## Approach

In order to allow points mentioned above, it was necessary to reorganize a bit the code that triggers the `quarto inspect` command and that, sub sequentially, uses the output to generate the deployment configuration, having specific checks for `_quarto.yml` picked up as entrypoint and extending the inspect output `struct` to account for directory scanning scenarios.

## User Impact

Users now will:
1. Get `pre-` and `post-` scripts included - if any - to the configuration on Quarto project inspection.
2. Users can select `_quarto.yml` as entrypoint and configuration will be properly generated.

## Automated Tests

New tests were created to cover this new functionality.

## Directions for Reviewers

Try publishing a Quarto website project, even better if it has `pre-render` and `post-render` scripts to confirm such files are included in the resulting configuration.

The jumpstart example of a Quarto website can be used as example.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

**Comment by sagerb** [comment]
@marcosnav The code within the PR is looking good, but I started hitting some issues with the quarto examples within `connect-content` repo, so I would like to have you test each of the quarto content types within the repo, as I think you'll want to make some changes.

I started with `connect-content/bundles/quarto-book-none`. After needing to fix up the `renv` issues (which are not within scope of your changes), my deployment (after picking `_quarto.yml` as the entrypoint) would not render successfully do to missing files. Since you've got changes within this code which adds additional files into the included file list, I think you should update the code to grab every file which `quarto inspect` returns.

In this case, I saw `quarto inspect` return:
```
{
  "quarto": {
    "version": "1.5.57"
  },
  "dir": "/Users/billsager/dev/connect-content/bundles/quarto-book-none",
  "engines": [
    "markdown"
  ],
  "config": {
    "project": {
      "type": "book",
      "lib-dir": "site_libs",
      "output-dir": "_book",
      "render": [
        "index.qmd",
        "intro.qmd",
        "summary.qmd",
        "references.qmd"
      ]
    },
    "book": {
      "title": "quarto-book-none",
      "author": "Jane Doe",
      "date": "2/9/2022",
      "chapters": [
        "index.qmd",
        "intro.qmd",
        "summary.qmd",
        "references.qmd"
      ],
      "render": [
        {
          "type": "chapter",
          "file": "index.qmd",
          "depth": 0
        },
        {
          "type": "chapter",
          "file": "intro.qmd",
          "number": 1,
          "depth": 0
        },
        {
          "type": "chapter",
          "file": "summary.qmd",
          "number": 2,
          "depth": 0
        },
        {
          "type": "chapter",
          "file": "references.qmd",
          "depth": 0
        }
      ]
    },
    "bibliography": "references.bib",
    "format": {
      "html": {
        "theme": "cosmo"
      }
    },
    "language": {},
    "website": {
      "title": "quarto-book-none",
      "sidebar": {
        "title": "quarto-book-none",
        "contents": [
          "index.qmd",
          "intro.qmd",
          "summary.qmd",
          "references.qmd"
        ],
        "style": "floating",
        "tools": []
      },
      "page-navigation": true
    }
  },
  "files": {
    "input": [
      "/Users/billsager/dev/connect-content/bundles/quarto-book-none/index.qmd",
      "/Users/billsager/dev/connect-content/bundles/quarto-book-none/intro.qmd",
      "/Users/billsager/dev/connect-content/bundles/quarto-book-none/summary.qmd",
      "/Users/billsager/dev/connect-content/bundles/quarto-book-none/references.qmd"
    ],
    "resources": [],
    "config": [
      "/Users/billsager/dev/connect-content/bundles/quarto-book-none/_quarto.yml"
    ],
    "configResources": [
      "/Users/billsager/dev/connect-content/bundles/quarto-book-none/references.bib"
    ]
  },
  "fileInformation": {
    "/Users/billsager/dev/connect-content/bundles/quarto-book-none/index.qmd": {
      "includeMap": [],
      "codeCells": []
    },
    "/Users/billsager/dev/connect-content/bundles/quarto-book-none/intro.qmd": {
      "includeMap": [],
      "codeCells": []
    },
    "/Users/billsager/dev/connect-content/bundles/quarto-book-none/summary.qmd": {
      "includeMap": [],
      "codeCells": []
    },
    "/Users/billsager/dev/connect-content/bundles/quarto-book-none/references.qmd": {
      "includeMap": [],
      "codeCells": []
    }
  }
}
```

The initial error I saw within the render logs on Connect was that `references.bib` was not included. 

If we are going to include all of the referenced files automatically for quarto projects, (at least the ones that quarto inspect does tell us about), then I think you'll want to make sure you parse out all of the locations in which the inspect results will return file references.

Let me know if you agree with me that we should address these additional file references within your PR. Thanks so much!

**Comment by marcosnav** [comment]
@sagerb Thanks for trying it out and noticing that. I tested out mainly the jumpstart examples and a couple other projects, I'll take a look to this other bundles to see other cases that we might be missing.

I do think that it makes sense to address some of these other file inclusions on this PR, I'll take another pass to the schema we have and see what we are missing.

**Comment by marcosnav** [comment]
Also, Quarto 1.6 was just released and it now supports a new `_brand.yml` file, I'll take a look and see if this new file is supported by default or if it has it's own new place within the inspect command output.

**Comment by marcosnav** [comment]
> Do you think we need to first capture the version of quarto and then deserialize into a version specific structure? Or are you seeing that they are simply adding additional fields vs. removing/changing ones?

@sagerb So far I haven't seen the need for versioning the structure, changes are additive. Specifically for the new `_brand.yml`, it is a special file like `_metadata.yml`, nothing brakes if it is not present and we just add it to the deployment if it exists, nothing happens if it exists and it is not used.

**Comment by marcosnav** [comment]
@sagerb PR ready for another look, with some more adjustments to identify and add project related resources.

**Comment by sagerb** [comment]
NOT YET COMPLETED... 

Validation details from projects in repo: `connect-content`, on `main`. Using Quarto v 1.6.39 on Mac, but v 1.5.57 on Connect Server.
- NOTE: should we call out the mismatch, like we do with Python?

1. `bundles/quarto-doc-none`
    - **success** (selected `bundles/quarto-doc-none/quarto-doc-none.qmd`)
2. `bundles/quarto-multidoc-proj-none`
    - **?????** Always rendered to be document 1, even though have tried three different entrypoints: `bundles/quarto-multidoc-proj-none/_quarto.yml`, `bundles/quarto-multidoc-proj-none/document1.qmd` and `bundles/quarto-multidoc-proj-none/document2.qmd`.
    - Would have expected w/ entrypoint selected as document2.qmd, that we would render and show document2?
3. `bundles/quarto-proj-none`
    - **success** Selected `bundles/quarto-proj-none/_quarto.yml` and updated existing deployment to `bundles/quarto-proj-none/quarto-proj-none.qmd`.
4. `bundles/quarto-proj-none-ojs`
    - **success** Selected `bundles/quarto-proj-none-ojs/quarto-proj-none-ojs.qmd` and updated existing deployment to `bundles/quarto-proj-none-ojs/_quarto.yml`
5. `bundles/quarto-proj-py`
    - **success** Selected `bundles/quarto-proj-py/quarto-proj-py.qmd` and updated to existing deployment to `bundles/quarto-proj-py/_quarto.yml`
6. `bundles/quarto-proj-r`
    - Repo has existing `renv` directory populated. Was unable to deploy, got error:
>Could not scan R packages from lockfile: renv.lock, R6: package not found in current libPaths; consider running renv::restore() to populate the renv library
NOTE: This seems to be another example of how we do require a working R environment to deploy?
    - **success** Selected `bundles/quarto-proj-r/_quarto.yml`
7. `bundles/quarto-proj-r-py`
    - **success** Selected `bundles/quarto-proj-r-py/quarto-proj-r-py.qmd`

**Comment by sagerb** [comment]
Summary of validation findings:

**Problem**: Not detecting `styles.css` and adding it to the file list, if do not pick `_quarto.yml` as entrypoint file. See finding #9 above, to see how `quarto inspect about.qmd` did return a reference to the file.

**Questions**
- Are findings within #2 expected?
- Multiple examples of how we need to either re-run `renv::restore()` or `renv::snapshot()` and restore packages (or not) to allow proper package discovery. Doesn't this conflict with the objective of not needing to be able to execute code?
- Did we want to update the entrypoint selection dialog to allow selection of directories (to allow Quarto directory/projects?)
- Should have quarto inspection found the dependency of `deps.R`? (See 11, 13, 15, and 16)
- Should we be warning when local quarto version doesn't match with what is on Connect Server?

**Comment by sagerb** [comment]
@marcosnav See my findings above. I think you should address the `problem` item above, as technically, it seems within reach. The other items I placed into `Questions`, just need some group discussion or actions.

**Comment by jonkeane** [comment]
> Multiple examples of how we need to either re-run renv::restore() or renv::snapshot() and restore packages (or not) to allow proper package discovery. Doesn't this conflict with the objective of not needing to be able to execute code?

This is _exactly the place_ where we are stuck currently given the ecosystem of manifest.json + needing more information than the renv.lock file has to send up to connect. We would like to live in a Connect world where this isn't a requirement, but today it is. So _today_ we do need to effectively be in a place (well the renv library does) where one could execute the code. But this isn't transitive: just because today we do effectively need to be in that state, that *doesn't mean* that executing the code is a requirement we should always assert/strive for in other situations or in the future if the manifest.json/renv.lock issue is solved. 

> NOTE: This seems to be another example of how we do require a working R environment to deploy? Should we detect this by running renv::status() and parsing the output, so we can show a quicker error?

I couldn't quite tell from the formatting if this was a quote of something somewhere or what. But, yes this sounds like a good idea. We almost certainly should not do it in this PR, but using `renv::status` to diagnose the renv setup (and then "just" passing whatever renv says to the user to resolve) would be an excellent way to get folks into an renv state that works for publishing.

**Review by sagerb — APPROVED** [review]
Thanks for making the latest set of changes. I've validated them and reviewed that code as well. Looks great!

I'm ok with putting off a discussion regarding the switch to simply always performing inspection upon the subdirectory of what has been selected as an entrypoint. It feels like something that would provide the same type of functionality as the IDE, so I'd recommend we investigate and discuss this further.

**Pull request merged**
